### ISSUE TITLE
貌似只有自带的人脸有效

### ISSUE THREAD

**Issue by whtc123** [lsy17096535/ncnn-vs2013#1]
貌似只有自带的人脸有效,用其他的人脸图片或者摄像头抓的图片就对不上

**Comment by panda-lab** [comment]
@whtc123 我用ncnn验证一下我的模型是不是可以在上面跑起来，没有加人脸检测的部分，那个图片是我自己截图的人脸，跟原始人脸框有偏差，如果你对视频做landmark，需要加上人脸加测部分，我用的dlib，参考：https://github.com/lsy17096535/face-landmark/blob/master/face_landmark.cpp

**Comment by whtc123** [comment]
感谢

**Comment by 82157402** [comment]
我将这个移植到android平台上，怎么标的点根本就不对了？这是为什么？

**Comment by panda-lab** [comment]
@82157402 代码发给我看一下？
