### ISSUE TITLE
方便请教一下网络方面的问题么？

### ISSUE THREAD

**Issue by yytzjgsu** [lsy17096535/ncnn-vs2013#5]
我看到网络激活函数是用的tanh+absval，请问这有什么出处么？是不是说做回归任务这样激活效果会好？

**Comment by panda-lab** [comment]
@yytzjgsu  实验结果感觉这样好一些

**Comment by yytzjgsu** [comment]
@lsy17096535 嗯，我就是对网络的激活函数不太明白，我看到你们的.param文件中卷积结构是这样的
Convolution      Conv1            1 1 data Conv1 20 5 1 1 2 1 500
TanH             ActivationTangH1 1 1 Conv1 ActivationTangH1
AbsVal           ActivationAbs1   1 1 ActivationTangH1 Abs1
为什么要连续两次激活？是为了让输出满足【0，1】区间么？那么这样做相比sigmoid有什么好处呢？
谢谢

**Comment by yytzjgsu** [comment]
@lsy17096535 好哒，谢谢解答。
