### ISSUE TITLE
代码没有改变，为啥关键点有点飘乱

### ISSUE THREAD

**Issue by Andrawzyf** [lsy17096535/ncnn-vs2013#9]
代码没有改变，在ubuntu环境编译可执行文件运行后，显示的关键点有点乱

**Comment by panda-lab** [comment]
这个是好久之前用ncnn做的，我记得改过ncnn的归一化代码，你可以尝试用新的ncnn编译使用。

**Comment by Andrawzyf** [comment]
@lsy17096535 新的ncnn mat.cpp里面的 substract_mean_normalize这个函数改了，改的只有两个入参了。。

**Comment by Andrawzyf** [comment]
@lsy17096535 还有ncnn版本的速度咋跑出来是400多毫秒。。。。。：（

**Comment by panda-lab** [comment]
用一下这个吧 https://github.com/zeusees/HyperLandmark 我们的新版
